### ISSUE TITLE
AllRowsReader crashes

### ISSUE THREAD

**Issue by orrgal1** [Netflix/astyanax#294]
trying to do this:

.....prepareQuery(cf)
                    .getAllRows()
                    .setRowLimit(1000)
                    .setRepeatLastToken(false)
                    .executeWithCallback(new RowCallback<String, String>() {
                        @Override
                        public void success(Rows<String, String> rows) {
                   .....

it starts running but eventually gets stuck.
in cassandra log i see this:

ERROR [Thrift:206] 2013-04-21 15:13:00,272 CustomTThreadPoolServer.java (line 217) Error occurred during processing of message.
java.lang.NumberFormatException: For input string: "154320106080083401870660964220041313141"
        at java.lang.NumberFormatException.forInputString(Unknown Source)
        at java.lang.Long.parseLong(Unknown Source)
        at java.lang.Long.valueOf(Unknown Source)
        at org.apache.cassandra.dht.Murmur3Partitioner$1.fromString(Murmur3Partitioner.java:188)
        at org.apache.cassandra.thrift.CassandraServer.get_range_slices(CassandraServer.java:941)
        at org.apache.cassandra.thrift.Cassandra$Processor$get_range_slices.getResult(Cassandra.java:3454)
        at org.apache.cassandra.thrift.Cassandra$Processor$get_range_slices.getResult(Cassandra.java:3442)
        at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:32)
        at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:34)
        at org.apache.cassandra.thrift.CustomTThreadPoolServer$WorkerProcess.run(CustomTThreadPoolServer.java:199)
        at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
ERROR [Thrift:213] 2013-04-21 15:13:00,276 CustomTThreadPoolServer.java (line 217) Error occurred during processing of message.
java.lang.NumberFormatException: For input string: "148810114953871735207984646094233139761"
        at java.lang.NumberFormatException.forInputString(Unknown Source)
        at java.lang.Long.parseLong(Unknown Source)
        at java.lang.Long.valueOf(Unknown Source)
        at org.apache.cassandra.dht.Murmur3Partitioner$1.fromString(Murmur3Partitioner.java:188)
        at org.apache.cassandra.thrift.CassandraServer.get_range_slices(CassandraServer.java:941)
        at org.apache.cassandra.thrift.Cassandra$Processor$get_range_slices.getResult(Cassandra.java:3454)
        at org.apache.cassandra.thrift.Cassandra$Processor$get_range_slices.getResult(Cassandra.java:3442)
        at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:32)
        at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:34)
        at org.apache.cassandra.thrift.CustomTThreadPoolServer$WorkerProcess.run(CustomTThreadPoolServer.java:199)
        at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

**Comment by ckalantzis** [comment]
Closing for no reply > year.
